accessControl:
  salt: vA0UQPZHRuluIYvch0zuNT1DwjnEVyac
api:
  key: 28FC79F04EEB4C9A806B2CC1D34745DF
appearance:
  name: Kossel
controls:
- children:
  - commands:
    - M906 X%(current_x)s
    - M909 X%(microstepping_x)s
    input:
    - default: 500
      name: Current X
      parameter: current_x
      slider:
        max: 2500
        min: 1
        step: 1
    - default: 4
      name: Microstepping X
      parameter: microstepping_x
      slider:
        max: 7
        min: 0
        step: 1
    layout: vertical
    name: Set
  - commands:
    - M906 Y%(current_y)s
    - M909 Y%(microstepping_y)s
    input:
    - default: 500
      name: Current Y
      parameter: current_y
      slider:
        max: 2500
        min: 1
        step: 1
    - default: 4
      name: Microstepping Y
      parameter: microstepping_y
      slider:
        max: 7
        min: 0
        step: 1
    layout: vertical
    name: Set
  - commands:
    - M906 Z%(current_z)s
    - M909 Z%(microstepping_z)s
    input:
    - default: 500
      name: Current Z
      parameter: current_z
      slider:
        max: 2500
        min: 1
        step: 1
    - default: 4
      name: Microstepping Z
      parameter: microstepping_z
      slider:
        max: 7
        min: 0
        step: 1
    layout: vertical
    name: Set
  - commands:
    - M906 E%(current_e)s
    - M909 E%(microstepping_e)s
    input:
    - default: 500
      name: Current E
      parameter: current_e
      slider:
        max: 2500
        min: 1
        step: 1
    - default: 4
      name: Microstepping E
      parameter: microstepping_e
      slider:
        max: 7
        min: 0
        step: 1
    layout: vertical
    name: Set
  - commands:
    - M906 H%(current_h)s
    - M909 H%(microstepping_h)s
    input:
    - default: 500
      name: Current H
      parameter: current_h
      slider:
        max: 2500
        min: 1
        step: 1
    - default: 4
      name: Microstepping H
      parameter: microstepping_h
      slider:
        max: 7
        min: 0
        step: 1
    layout: vertical
    name: Set
  layout: vertical
  name: Stepper current and microstepping
- children:
  - commands:
    - M569 X%(direction_x)s
    - M92  X%(steps_pr_mm_x)s
    input:
    - default: 10
      name: Steps pr mm X
      parameter: steps_pr_mm_x
    - default: 1
      name: Invert X
      parameter: direction_x
      slider:
        max: 1
        min: -1
        step: 2
    layout: vertical
    name: Set
  - commands:
    - M569 Y%(direction_y)s
    - M92  Y%(steps_pr_mm_y)s
    input:
    - default: 10
      name: Steps pr mm Y
      parameter: steps_pr_mm_y
    - default: 1
      name: Invert Y
      parameter: direction_y
      slider:
        max: 1
        min: -1
        step: 2
    layout: vertical
    name: Set
  - commands:
    - M569 Z%(direction_z)s
    - M92  Z%(steps_pr_mm_z)s
    input:
    - default: 10
      name: Steps pr mm Z
      parameter: steps_pr_mm_z
    - default: 1
      name: Invert Z
      parameter: direction_z
      slider:
        max: 1
        min: -1
        step: 2
    layout: vertical
    name: Set
  - commands:
    - M569 E%(direction_e)s
    - M92  E%(steps_pr_mm_e)s
    input:
    - default: 10
      name: Steps pr mm E
      parameter: steps_pr_mm_e
    - default: 1
      name: Invert E
      parameter: direction_e
      slider:
        max: 1
        min: -1
        step: 2
    layout: vertical
    name: Set
  - commands:
    - M569 H%(direction_h)s
    - M92  H%(steps_pr_mm_h)s
    input:
    - default: 10
      name: Steps pr mm H
      parameter: steps_pr_mm_h
    - default: 1
      name: Invert H
      parameter: direction_h
      slider:
        max: 1
        min: -1
        step: 2
    layout: vertical
    name: Set
  layout: vertical
  name: Stepper steps pr mm and direction
feature:
  modelSizeDetection: false
  printCancelConfirmation: false
folder:
  timelapse: /home/octo/OctoData/timelapse
  timelapse_tmp: /home/octo/OctoData/timelapse/tmp
  uploads: /usr/share/models
gcodeViewer: {}
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1522320900
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1521023400
      _plugins:
        read_until: 1523232000
      _releases:
        read_until: 1523285400
  cura:
    cura_engine: /usr/bin/CuraEngine
  discovery:
    upnpUuid: d0867588-42b7-481e-88a2-206e9316b3f6
  simpleemergencystop:
    confirmationDialog: false
  softwareupdate:
    _config_version: 5
    check_providers:
      filemanager: filemanager
      simpleemergencystop: simpleemergencystop
      slicer: slicer
    checks:
      Kamikaze:
        checkout_folder: /usr/src/Kamikaze2
        restart: echo "Kamikaze dummy restart"
        type: git_commit
        update_script: /usr/src/Kamikaze2/update-kamikaze.sh
      Redeem:
        checkout_folder: /usr/src/redeem
        restart: echo "Redeem dummy restart"
        type: git_commit
        update_script: '{python} "/usr/src/redeem/update-redeem.py" --python="{python}"
          --sudo "{folder}" "{target}"'
      Toggle:
        checkout_folder: /usr/src/toggle
        restart: echo "Toggle dummy restart"
        type: git_commit
        update_script: '{python} "/usr/src/toggle/update-toggle.py" --python="{python}"
          "{folder}" "{target}"'
      octoprint:
        checkout_folder: /home/octo/OctoPrint
        prerelease: false
printerParameters: {}
printerProfiles: {}
serial:
  additionalPorts:
  - /dev/octoprint_1
  baudrate: 115200
  port: /dev/octoprint_1
  timeout: {}
server:
  commands:
    serverRestartCommand: sudo systemctl restart octoprint.service
    systemRestartCommand: sudo reboot
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  secretKey: RnUkld1QNaBoe6KGSGcA1sMSSMgGmdRd
  seenWizards:
    corewizard: 1
system:
  actions:
  - action: restart_redeem
    command: sudo systemctl restart redeem.service
    name: Restart Redeem
  - action: restart_toggle
    command: sudo systemctl restart toggle.service
    name: Restart Toggle
  - action: restart mjpg
    command: sudo systemctl restart mjpg.service
    name: Restart Mjpg
temperature: {}
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://10.0.45.2:8080/?action=snapshot
  stream: http://10.0.45.2:8080/?action=stream
  timelapse:
    fps: 25
    options:
      capturePostRoll: true
      interval: 10
    postRoll: 0
    type: timed
